version: '3.7'

services:
  judge0-server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    environment:
      - JUDGE0_CONFIG_FILE=/judge0.conf
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    environment:
      - JUDGE0_CONFIG_FILE=/judge0.conf
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-db:
    image: postgres:13.0
    env_file: judge0.conf
    restart: always
    volumes:
      - judge0-postgres-data:/var/lib/postgresql/data/

  judge0-redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    restart: always
    volumes:
      - judge0-redis-data:/data

volumes:
  judge0-postgres-data:
  judge0-redis-data: