# Generated by Django 4.2.7 on 2026-04-02 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_auto_applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('custom_weights', models.JSONField(default=dict)),
                ('successful_hire_patterns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('job_type', models.CharField(max_length=50)),
                ('salary_range', models.JSONField(default=dict)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='active', max_length=50)),
                ('total_applicants', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_type', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('AI/ML', 'AI/ML'), ('Design', 'Design'), ('Soft Skills', 'Soft Skills'), ('DevOps', 'DevOps'), ('Data Science', 'Data Science')], max_length=50)),
                ('verification_method', models.CharField(default='self_reported', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('university_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('preferences', models.JSONField(default=dict)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('github_verified', models.BooleanField(default=False)),
                ('github_score', models.IntegerField(default=0)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_complete_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('activity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_frequency', models.IntegerField(default=0)),
                ('total_session_duration', models.IntegerField(default=0)),
                ('ab_test_group', models.CharField(default='control', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBehaviorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_type', models.CharField(max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('complexity_score', models.IntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.student')),
                ('tech_stack', models.ManyToManyField(to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='MatchExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_breakdown', models.JSONField()),
                ('recommendations', models.JSONField(default=list)),
                ('radar_chart_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='core.application')),
                ('skill_gaps', models.ManyToManyField(blank=True, to='core.skill')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(to='core.skill'),
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_times', models.JSONField(default=list)),
                ('finalized_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='core.student')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.student'),
        ),
        migrations.CreateModel(
            name='AIFeedbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_weights', models.JSONField(default=dict)),
                ('adjusted_weights', models.JSONField(default=dict)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='core.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_logs', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=20)),
                ('verified_via', models.CharField(blank=True, max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
