# Generated by Django 4.2.7 on 2026-04-02 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='samir7232', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='samir7232', max_length=255),
            preserve_default=False,
        ),
    ]
