# Generated by Django 4.2.7 on 2026-04-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_description_company_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentskill',
            name='verified_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
