# Generated by Django 4.2.7 on 2026-04-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentskill_verified_via'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('student', 'title')},
        ),
    ]
