# Generated by Django 4.2.7 on 2026-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='awarded_actions',
            field=models.JSONField(default=list),
        ),
    ]
