# Generated by Django 4.2.7 on 2026-06-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
