# Generated by Django 4.2.7 on 2026-06-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aiinterview_cheating_log'),
        ('core', '0017_delete_chatmessage'),
    ]

    operations = [
    ]
