# Generated by Django 5.2.17 on 2026-10-02 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


def check_duplicate_applications(apps, schema_editor):
    from django.db.models import Count
    Application = apps.get_model('core', 'Application')
    duplicates = (Application.objects.using(schema_editor.connection.alias)
                  .values('student_id', 'job_id').annotate(n=Count('pk')).filter(n__gt=1))
    if duplicates.exists():
        raise RuntimeError('Duplicate applications exist. Back up the database, run check_setup, '
                           'and reconcile their related assessments/interviews before retrying. '
                           'This migration does not delete existing records.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_application_vetting_score'),
    ]

    operations = [
        migrations.RunPython(check_duplicate_applications, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(max_length=20)),
                ('sender_id', models.UUIDField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'job'), name='unique_student_job_application'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('student', 'github_repo_id'), name='unique_student_github_repo'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.application'),
        ),
    ]
