# Generated by Django 4.2.7 on 2026-04-06 04:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_interviewslot_scheduledinterview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VettingChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('starter_code', models.TextField()),
                ('test_cases', models.JSONField(default=list)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('time_limit_minutes', models.IntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skill_tags', models.JSONField(default=list)),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vetting_challenge', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='VettingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('max_duration_minutes', models.IntegerField(default=45)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('copy_paste_attempts', models.IntegerField(default=0)),
                ('fullscreen_exits', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('cheating_detected', 'Cheating Detected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vetting_session', to='core.application')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vetting.vettingchallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetting_sessions', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='VettingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer1_test_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('layer2_static_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('layer3_ai_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('final_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('test_case_results', models.JSONField(default=list)),
                ('static_analysis_report', models.JSONField(default=dict)),
                ('ai_feedback', models.TextField(blank=True)),
                ('code_quality_issues', models.JSONField(default=list)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vetting_result', to='core.application')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='vetting.vettingsession')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
                ('execution_output', models.TextField(blank=True)),
                ('execution_error', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.FloatField(blank=True, null=True)),
                ('test_cases_passed', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='vetting.vettingsession')),
            ],
        ),
    ]
